image: gradle:latest

cache:
  paths:
    - .m2/repository/
    - target/

test:
  stage: test
  script:
    - gradle clean test

deploy:
  stage: deploy
  script:
    - gradle io.qameta.allure:allure-gradle:report

